[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "cd client && npm ci",
  "cd ../server && npm ci --omit=dev"
]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "cd server && npm start"
